import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import amplifyconfig from "../src/aws-exports";
import { Amplify } from "aws-amplify";

const inter = Inter({ subsets: ['latin'] })
Amplify.configure({ ...amplifyconfig, ssr: true });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
